### ISSUE TITLE
Simpler installation instructions

### ISSUE THREAD

**Issue by louisaslett** [phuongquan/daiquiri#1]
This is more feedback than an issue (I could fork and do a pull request, but it's simple so I figured an issue was easier).  On the Readme it suggests downloading a .tar.gz and installing manually, but I'd like to suggest users are pointed to the simple one-line `remotes` approach to installing from Github:

```
remotes::install_github("phuongquan/daiquiri")
```

Hope this helps and keep up the nice work!

**Comment by phuongquan** [comment]
Hi Louis, thanks for your feedback. The reason for the extended instructions were to help users install the latest _release_ (which has vignettes pre-built) rather than the development version (which doesn't build vignettes by default and is also likely to be more buggy). This was only meant as a workaround until I get it on CRAN. I agree that it's not clear though so will look at updating the readme.
